#!/bin/bash

THIS=$(basename $0)
cmd="$1"

CFN_STACK_NAME=minecraft-stack
#CFN_TEMPLATE=file://cfn/mc.yml
CFN_TEMPLATE=./cfn/mc.yml
CFN_PARAMETERS=./cfn/mc.parameters
CFN_EXTRAS="--capabilities CAPABILITY_IAM"

#AWS_CMD="aws cloudformation update-stack --stack-name $CFN_STACK_NAME --template-body $CFN_TEMPLATE $CFN_EXTRAS"
AWS_CMD="aws --profile gato-feo cloudformation"

# ---------------------------------------------------------------------------
mc_start() {
    echo starting...
    $AWS_CMD update-stack \
       --stack-name $CFN_STACK_NAME \
       --template-body file://${CFN_TEMPLATE} \
       --parameters file://${CFN_PARAMETERS} \
       $CFN_EXTRAS
}

# ---------------------------------------------------------------------------
mc_stop() {
    echo stopping...
    $AWS_CMD update-stack \
       --stack-name $CFN_STACK_NAME \
       --template-body file://${CFN_TEMPLATE} \
       --parameters file://${CFN_PARAMETERS} \
       $CFN_EXTRAS

       #--parameters "ParameterKey=ServerState,ParameterValue=Stopped" \
}

# ---------------------------------------------------------------------------
mc_status() {
    echo status...
    $AWS_CMD describe-stacks --stack-name $CFN_STACK_NAME | grep StackStatus
}

# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

case $cmd in
    start)
        mc_start
        ;;
    stop)
        mc_stop
        ;;
    status)
        mc_status
        ;;
    *)
        echo "$THIS [start|stop|status]"
        exit 0
        ;;
esac


